-- ============================================================
--  MIRAJ - COMPLETE DATABASE BUILD (single file)
--
--  Paste into the Supabase SQL editor of MIRAJ's own project and
--  run once. Equivalent to `npm run db:setup`, for when Node is
--  not available.
--
--  = supabase/miraj-setup.sql  (18 base tables + 3 RPCs)
--  + supabase/migrations/0034..0060, in order
--
--  Safe to re-run: it drops and recreates "public" first, so a
--  failed partial run is cleaned up by simply running it again.
--
--  WARNING: DROPS AND RECREATES the "public" schema. Every table
--  in the target project is destroyed.
-- ============================================================


-- ===================== miraj-setup.sql =====================

-- ============================================================
--  Miraj database setup - BASE schema: 18 tables, 3 RPC
--  functions (daily_pnl, per_product_stats,
--  product_monthly_delivery) and the monthly_manual_expenses
--  table. Migrations 0034-0059 take this to 33 tables.
--
--  Run this FIRST, once, in Miraj's own Supabase project
--  (SQL editor, or scripts/setup-database.mjs).
--
--  This is only the base. Migrations 0034..0058 add everything
--  after it (product variants, BOM, chat orders, purchasing,
--  product aliases, self-delivered, RLS, ...) and MUST be applied
--  in order afterwards. scripts/setup-database.mjs does both.
--
--  WARNING: this drops and recreates the "public" schema.
-- ============================================================

-- ---------- tables ----------
-- Miraj owns this Supabase project outright, so its tables live in "public",
-- which Supabase exposes over the API by default (no Exposed-schemas change
-- needed, unlike the named-schema siblings).
--
-- Resetting the schema wipes EVERY table in this project - only ever run this
-- against Miraj's own project, and only on a fresh/disposable database.
drop schema if exists public cascade;
create schema public;

-- Recreating "public" drops the grants Supabase ships with it; restore them
-- before creating anything, or the dashboard and the API roles lose access.
grant usage on schema public to postgres, anon, authenticated, service_role;
grant all on schema public to postgres, anon, authenticated, service_role;

-- ---------- model_groups (a "model" above individual color products) ----------
create table public.model_groups (
  id bigint generated always as identity primary key,
  name text not null,
  unit_cost numeric(12,2),
  refund_rate_override numeric(6,4),
  damage_rate_override numeric(6,4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- products (one row per Shopify product / color) ----------
create table public.products (
  id bigint generated always as identity primary key,
  shopify_product_id bigint unique,
  name text not null,
  sku text,
  model_group_id bigint references public.model_groups(id),
  current_price numeric(12,2),
  price_synced_at timestamptz,
  unit_cost_override numeric(12,2),
  status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- orders ----------
create table public.orders (
  id bigint generated always as identity primary key,
  shopify_order_id bigint unique not null,
  order_number text not null,
  order_created_at timestamptz not null,
  egypt_day date not null,
  total_price numeric(12,2),
  currency text default 'EGP',
  governorate_shopify text,
  cancelled_at timestamptz,
  financial_status text,
  shipping_fee_charged numeric(12,2),

  bosta_tracking_number text,
  outcome text check (outcome in ('in_transit','delivered','failed_rto','exchange','pickup_return','cancelled_return')),
  outcome_governorate text,
  attempt_number int default 1,
  cod_amount_collected numeric(12,2),
  resolved_at timestamptz,
  stock_received_at timestamptz,
  last_bosta_sync_at timestamptz,
  bosta_picked_up_day date,

  courier text check (courier in ('bosta', 'movers')),
  movers_record_date date,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index orders_egypt_day_idx on public.orders (egypt_day);
create index orders_order_number_idx on public.orders (order_number);
create index orders_bosta_picked_up_day_idx on public.orders (bosta_picked_up_day);

-- ---------- order_line_items ----------
create table public.order_line_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  shopify_line_item_id bigint,
  shopify_product_id bigint,
  product_title_raw text,
  quantity int not null check (quantity > 0),
  unit_price numeric(12,2) not null,

  -- valuation engine outputs
  revenue numeric(12,2),
  cost_of_goods numeric(12,2),
  allocated_courier_fee numeric(12,2),
  allocated_cod_cash_fee numeric(12,2),
  allocated_open_package_fee numeric(12,2),
  packing_cost numeric(12,2),
  refund_adjustment numeric(12,2),
  damage_adjustment numeric(12,2),
  success_rate_used numeric(6,4),
  expected_margin numeric(12,2),
  realized_margin numeric(12,2),
  fee_breakdown jsonb,
  margin_computed_at timestamptz,

  created_at timestamptz not null default now()
);
create index order_line_items_order_id_idx on public.order_line_items (order_id);
create index order_line_items_product_id_idx on public.order_line_items (product_id);
create unique index order_line_items_shopify_line_item_id_key
  on public.order_line_items (shopify_line_item_id);

-- ---------- bosta_events (append-only courier audit trail) ----------
create table public.bosta_events (
  id bigint generated always as identity primary key,
  order_id bigint references public.orders(id),
  bosta_delivery_id text not null,
  business_reference text,
  bosta_type text,
  bosta_state text,
  attempt_number int,
  cod_amount numeric(12,2),
  governorate text,
  event_timestamp timestamptz,
  raw_payload jsonb,
  synced_at timestamptz not null default now()
);
create index bosta_events_order_id_idx on public.bosta_events (order_id);
create unique index bosta_events_delivery_id_key on public.bosta_events (bosta_delivery_id);

-- ---------- governorate_fees ----------
create table public.governorate_fees (
  governorate text primary key,
  zone text,
  updated_at timestamptz not null default now()
);
insert into public.governorate_fees (governorate) values
  ('Cairo'), ('Alexandria'), ('Giza'), ('Qalyubia'), ('Port Said'), ('Suez'),
  ('Dakahlia'), ('Sharqia'), ('Gharbia'), ('Monufia'), ('Beheira'), ('Ismailia'),
  ('Damietta'), ('Kafr El Sheikh'), ('Faiyum'), ('Beni Suef'), ('Minya'), ('Asyut'),
  ('Sohag'), ('Qena'), ('Aswan'), ('Luxor'), ('Red Sea'), ('New Valley'),
  ('Matrouh'), ('North Sinai'), ('South Sinai');

-- ---------- bosta_fee_matrix (zone x size price grid, VAT-inclusive) ----------
create table public.bosta_fee_matrix (
  zone text not null,
  shipment_size text not null,
  deliver numeric(12,2) not null,
  exchange numeric(12,2) not null,
  return_pickup numeric(12,2) not null,
  cash_collection numeric(12,2) not null,
  return_to_origin numeric(12,2) not null,
  updated_at timestamptz not null default now(),
  primary key (zone, shipment_size)
);

-- ---------- settings (single row, id = 1) ----------
create table public.settings (
  id int primary key default 1 check (id = 1),
  vat_multiplier numeric(6,4) not null default 1.14,
  cod_cash_fee_pct numeric(6,4) not null default 0,
  packing_cost_per_unit numeric(12,2) not null default 12,
  exchange_fee_base numeric(12,2) not null default 0,
  pickup_fee_base numeric(12,2) not null default 0,
  pickup_cash_refund_pct numeric(6,4) not null default 0,
  refund_rate_default numeric(6,4) not null default 0.03,
  damage_rate_default numeric(6,4) not null default 0.03,
  calibration_min_sample int not null default 150,
  calibration_min_ignore int not null default 10,
  attempt2_factor numeric(6,4) not null default 0.6,
  attempt3plus_factor numeric(6,4) not null default 0.25,
  default_box_size_tier text not null default 'Small & Medium'
    check (default_box_size_tier in ('Small & Medium','Large','X-Large','XXL (White Bag)','Light Bulky','Heavy Bulky')),
  default_success_rate_estimate numeric(6,4) not null default 0.70,
  bosta_open_package_fee numeric(12,2) not null default 7.00,
  bosta_open_package_vat_pct numeric(6,4) not null default 0.14,
  salary_employee1_monthly numeric(12,2) not null default 5000.00,
  salary_employee2_pct numeric(6,4) not null default 0.07,
  rent_monthly numeric(12,2) not null default 8000.00,
  transportation_per_day numeric(12,2) not null default 32.00,
  record_data_synced_at timestamptz,
  updated_at timestamptz not null default now()
);
insert into public.settings (id) values (1);

-- ---------- product_success_rates (calibrated per model) ----------
create table public.product_success_rates (
  model_group_id bigint not null references public.model_groups(id),
  as_of_date date not null,
  raw_rate numeric(6,4),
  resolved_sample_size int,
  store_wide_rate numeric(6,4),
  blended_rate numeric(6,4),
  attempt_adjusted_rates jsonb,
  created_at timestamptz not null default now(),
  primary key (model_group_id, as_of_date)
);

-- ---------- sync_state ----------
create table public.sync_state (
  source text primary key,
  last_synced_at timestamptz,
  cursor text,
  updated_at timestamptz not null default now()
);
insert into public.sync_state (source) values ('shopify'), ('bosta'), ('meta');

-- ---------- ad_spend (mapped to a model) ----------
create table public.ad_spend (
  id bigint generated always as identity primary key,
  date date not null,
  ad_id text,
  adset_id text not null,
  adset_name text,
  model_group_id bigint references public.model_groups(id),
  spend numeric(12,2) not null,
  currency text default 'EGP',
  -- traffic source the spend came from ('meta' | 'tiktok'); splits the P&L
  -- ad-spend line (see src/lib/reports/daily-pnl.ts, src/lib/tiktok-spend.ts).
  source text not null default 'meta',
  synced_at timestamptz not null default now(),
  unique (date, adset_id, ad_id)
);

-- ---------- monthly_delivery_rates (store-wide, per calendar month) ----------
create table public.monthly_delivery_rates (
  month date primary key,
  resolved_count int not null,
  delivered_count int not null,
  rate numeric(6,4) not null,
  computed_at timestamptz not null default now()
);

-- ---------- sku_monthly_delivery_rates (per product, per month) ----------
create table public.sku_monthly_delivery_rates (
  product_id bigint not null references public.products(id),
  month date not null,
  resolved_count int not null,
  delivered_count int not null,
  rate numeric(6,4) not null,
  created_at timestamptz not null default now(),
  primary key (product_id, month)
);

-- ---------- account_types (chart of accounts for Record Data) ----------
create table public.account_types (
  id bigint generated always as identity primary key,
  name text not null unique,
  type text not null check (type in ('income', 'expense')),
  created_at timestamptz not null default now()
);
insert into public.account_types (name, type) values
  ('Ta7selat', 'income'),
  ('Tasne3', 'expense'),
  ('Marketing', 'expense'),
  ('Subscriptions', 'expense'),
  ('Packaging', 'expense'),
  ('Transportation', 'expense'),
  ('Salary', 'expense'),
  ('Bosta', 'income'),
  ('Refund', 'expense'),
  ('Media Buyer', 'expense'),
  ('Moverz', 'income'),
  ('Other Income', 'income'),
  ('Other Expense', 'expense')
on conflict (name) do nothing;

-- ---------- recorded_transactions (manual ledger) ----------
create table public.recorded_transactions (
  id bigint generated always as identity primary key,
  date date not null,
  account_type_id bigint not null references public.account_types(id),
  type text not null check (type in ('income', 'expense')),
  description text,
  amount numeric(12,2) not null check (amount > 0),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- ---------- users (app login accounts) ----------
create table public.users (
  id bigint generated always as identity primary key,
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('owner', 'staff')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- model_group_cost_history (effective-dated cost timeline) ----------
create table public.model_group_cost_history (
  id bigint generated always as identity primary key,
  model_group_id bigint not null references public.model_groups(id),
  unit_cost numeric(12,2) not null,
  effective_from date not null,
  created_at timestamptz not null default now()
);
create index model_group_cost_history_model_idx
  on public.model_group_cost_history (model_group_id, effective_from);

-- ---------- ad_model_assignments (ad_id -> model mapping) ----------
create table public.ad_model_assignments (
  ad_id text primary key,
  model_group_id bigint not null references public.model_groups(id),
  created_at timestamptz not null default now()
);

-- ---------- grants so the Supabase API roles can use the schema ----------
grant usage on schema public to postgres, anon, authenticated, service_role;
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;

notify pgrst, 'reload schema';

-- confirmation: should list all 18 Miraj tables
select table_name from information_schema.tables where table_schema = 'public' order by table_name;

-- ---------- RPC: daily-pnl ----------
-- Aggregates the daily P&L in the DATABASE (per effective day) so the app reads
-- ~180 day rows instead of pulling 126k line-items on every page load.
-- p_mode: 'performance' (buckets by egypt_day) or 'actual' (by courier pickup /
-- movers record date; orders with no courier are excluded).
-- Mirrors getMatureRows() in src/lib/reports/daily-pnl.ts exactly:
--   revenue/COGS = delivered orders only; shipping fee + courier fees on the
--   non-returned side; returned orders' courier+open-package go to bosta_penalty.
drop function if exists public.daily_pnl(text);
create or replace function public.daily_pnl(p_mode text)
returns table (
  day date,
  orders_placed bigint,
  orders_resolved bigint,
  delivered_count bigint,
  items_sold bigint,
  revenue numeric,
  cogs numeric,
  gross_revenue numeric,
  gross_cogs numeric,
  packaging numeric,
  bosta_penalty numeric,
  bosta_fees_paid numeric,
  shipping_fee_charged numeric
)
language sql
stable
as $$
  with ord as (
    select
      o.id,
      case
        when p_mode = 'performance' then o.egypt_day
        when o.courier = 'movers' then o.movers_record_date
        when o.courier = 'bosta' then o.bosta_picked_up_day
        else null
      end as eff_day,
      o.outcome,
      o.shipping_fee_charged
    from public.orders o
    where o.cancelled_at is null
  ),
  ord2 as (select * from ord where eff_day is not null),
  order_agg as (
    select
      eff_day as day,
      count(*) as orders_placed,
      count(*) filter (where outcome in ('delivered','failed_rto','exchange','pickup_return')) as orders_resolved,
      count(*) filter (where outcome = 'delivered') as delivered_count,
      sum(case when outcome is distinct from 'failed_rto' then coalesce(shipping_fee_charged,0) else 0 end) as shipping_fee_charged
    from ord2
    group by eff_day
  ),
  line_agg as (
    select
      ord2.eff_day as day,
      sum(l.quantity) as items_sold,
      sum(case when ord2.outcome = 'delivered' then coalesce(l.revenue,0) else 0 end) as revenue,
      sum(case when ord2.outcome = 'delivered'
               then coalesce(l.cost_of_goods,0) - coalesce(l.refund_adjustment,0) - coalesce(l.damage_adjustment,0)
               else 0 end) as cogs,
      sum(coalesce(l.revenue,0)) as gross_revenue,
      sum(coalesce(l.cost_of_goods,0)) as gross_cogs,
      sum(coalesce(l.packing_cost,0)) as packaging,
      sum(case when ord2.outcome = 'failed_rto'
               then coalesce(l.allocated_courier_fee,0) + coalesce(l.allocated_open_package_fee,0)
               else 0 end) as bosta_penalty,
      sum(case when ord2.outcome is distinct from 'failed_rto'
               then coalesce(l.allocated_courier_fee,0) + coalesce(l.allocated_open_package_fee,0) + coalesce(l.allocated_cod_cash_fee,0)
               else 0 end) as bosta_fees_paid
    from ord2
    join public.order_line_items l on l.order_id = ord2.id
    group by ord2.eff_day
  )
  select
    coalesce(oa.day, la.day) as day,
    coalesce(oa.orders_placed, 0),
    coalesce(oa.orders_resolved, 0),
    coalesce(oa.delivered_count, 0),
    coalesce(la.items_sold, 0),
    coalesce(la.revenue, 0),
    coalesce(la.cogs, 0),
    coalesce(la.gross_revenue, 0),
    coalesce(la.gross_cogs, 0),
    coalesce(la.packaging, 0),
    coalesce(la.bosta_penalty, 0),
    coalesce(la.bosta_fees_paid, 0),
    coalesce(oa.shipping_fee_charged, 0)
  from order_agg oa
  full outer join line_agg la on oa.day = la.day;
$$;

grant execute on function public.daily_pnl(text) to anon, authenticated, service_role;

-- ---------- RPC: per-product ----------
-- Aggregates per-product stats in the DATABASE for the Analysis by Product page,
-- so the app doesn't pull ~126k line-items on every load. Covers the MATURE range
-- only; the still-open month is projected in-app (per-SKU delivery rate).
-- p_mode: 'performance' (egypt_day) or 'actual' (courier pickup / movers date).
-- Mirrors getPerProductReport's mature branch: revenue/cogs use stored per-line
-- values (all outcomes), placed = line-item count, resolved = final-outcome count.
drop function if exists public.per_product_stats(text, date, date);
create or replace function public.per_product_stats(p_mode text, p_from date, p_to date)
returns table (
  product_id bigint,
  orders_placed bigint,
  orders_resolved bigint,
  items_sold bigint,
  revenue numeric,
  cogs numeric
)
language sql
stable
as $$
  with ord as (
    select
      o.id,
      case
        when p_mode = 'performance' then o.egypt_day
        when o.courier = 'movers' then o.movers_record_date
        when o.courier = 'bosta' then o.bosta_picked_up_day
        else null
      end as eff_day,
      o.outcome
    from public.orders o
    where o.cancelled_at is null
  ),
  ord2 as (
    select * from ord where eff_day is not null and eff_day >= p_from and eff_day <= p_to
  )
  select
    l.product_id,
    count(*) as orders_placed,
    count(*) filter (where ord2.outcome in ('delivered','failed_rto','exchange','pickup_return')) as orders_resolved,
    sum(coalesce(l.quantity, 0)) as items_sold,
    sum(coalesce(l.revenue, 0)) as revenue,
    sum(coalesce(l.cost_of_goods, 0)) as cogs
  from ord2
  join public.order_line_items l on l.order_id = ord2.id
  where l.product_id is not null
  group by l.product_id;
$$;

grant execute on function public.per_product_stats(text, date, date) to anon, authenticated, service_role;

-- ---------- RPC: product-monthly-delivery ----------
-- Per-product, per-month delivery counts for the Bosta > Delivery Rate tab.
-- One row per (product, month): how many order-lines for that product were
-- placed that month (by placement date, excluding cancelled) and how many were
-- delivered. The app computes rate = delivered / placed. Run once in the
-- Supabase SQL editor.
create or replace function public.product_monthly_delivery()
returns table (product_id bigint, month text, placed bigint, delivered bigint)
language sql
stable
as $$
  select
    li.product_id::bigint                                          as product_id,
    to_char(o.egypt_day, 'YYYY-MM')                                as month,
    count(*)::bigint                                               as placed,
    count(*) filter (where o.outcome = 'delivered')::bigint        as delivered
  from public.order_line_items li
  join public.orders o on o.id = li.order_id
  where li.product_id is not null
    and o.cancelled_at is null
  group by li.product_id, to_char(o.egypt_day, 'YYYY-MM');
$$;

-- ---------- RPC: monthly-manual-expenses ----------
-- Manually-entered monthly P&L values (owner types them in the Income
-- Statement). One row per (month, account). Computed lines (Shipping
-- Differences, Bosta Penalty) are NOT stored here.
create table if not exists public.monthly_manual_expenses (
  month date not null,          -- first day of the month
  account text not null,        -- e.g. 'salaries', 'rent', 'tax'
  amount numeric(14,2) not null default 0,
  updated_at timestamptz not null default now(),
  primary key (month, account)
);

grant all on public.monthly_manual_expenses to anon, authenticated, service_role;


-- ===================== 0034_product_cost_structure.sql =====================

-- Product List cost structure (the 3-tab cost tool).
-- Each single product has a base cost (before packaging) plus the packaging
-- types attached to it; each bundle is built from member single products.
-- A product's built cost (single = base + packaging, bundle = sum of members)
-- feeds the margin engine as its unit cost.

alter table public.products
  add column if not exists is_bundle boolean not null default false,
  add column if not exists base_cost numeric(12,2);

-- Reusable packaging types with a unit cost (e.g. box, tape, sticker).
create table if not exists public.packaging_types (
  id bigint generated always as identity primary key,
  name text not null unique,
  unit_cost numeric(12,2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Which packaging types a single product uses (quantity defaults to 1).
create table if not exists public.product_packaging (
  product_id bigint not null references public.products(id) on delete cascade,
  packaging_type_id bigint not null references public.packaging_types(id) on delete cascade,
  quantity numeric(12,2) not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (product_id, packaging_type_id)
);

-- Which single products (and how many) make up a bundle.
create table if not exists public.bundle_items (
  bundle_product_id bigint not null references public.products(id) on delete cascade,
  member_product_id bigint not null references public.products(id) on delete cascade,
  quantity numeric(12,2) not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (bundle_product_id, member_product_id),
  constraint bundle_not_self check (bundle_product_id <> member_product_id)
);

create index if not exists product_packaging_product_idx on public.product_packaging (product_id);
create index if not exists bundle_items_bundle_idx on public.bundle_items (bundle_product_id);

notify pgrst, 'reload schema';


-- ===================== 0035_actual_delivered_basis.sql =====================

-- The "Actual" P&L view now means orders delivered on Bosta (outcome =
-- 'delivered'), dated by order day (egypt_day). Courier is never recorded on
-- Miraj orders (always null), so the old courier-pickup basis made Actual
-- empty. Revenue, COGS, orders count and items count all come from delivered
-- orders. The still-open month keeps its rate projection (handled in the app,
-- getOpenMonthRows, not here). Performance mode is unchanged.
--
-- Dropped first: this changes the function's OUT columns, and Postgres refuses
-- to "create or replace" a function whose return type differs (42P13). Every
-- other daily_pnl migration already does this; these two were the exceptions,
-- which only surfaced when the whole chain was replayed onto a fresh database.
drop function if exists public.daily_pnl(text);
create or replace function public.daily_pnl(p_mode text)
returns table (
  day date,
  orders_placed bigint,
  orders_resolved bigint,
  delivered_count bigint,
  items_sold bigint,
  revenue numeric,
  cogs numeric,
  gross_revenue numeric,
  gross_cogs numeric,
  packaging numeric,
  bosta_penalty numeric,
  bosta_fees_paid numeric,
  shipping_fee_charged numeric
)
language sql
stable
as $$
  with ord as (
    select
      o.id,
      case
        when p_mode = 'performance' then o.egypt_day
        when o.outcome = 'delivered' then o.egypt_day  -- actual: delivered orders only, dated by order day
        else null
      end as eff_day,
      o.outcome,
      o.shipping_fee_charged
    from public.orders o
    where o.cancelled_at is null
  ),
  ord2 as (select * from ord where eff_day is not null),
  order_agg as (
    select
      eff_day as day,
      count(*) as orders_placed,
      count(*) filter (where outcome in ('delivered','failed_rto','exchange','pickup_return')) as orders_resolved,
      count(*) filter (where outcome = 'delivered') as delivered_count,
      sum(case when outcome is distinct from 'failed_rto' then coalesce(shipping_fee_charged,0) else 0 end) as shipping_fee_charged
    from ord2
    group by eff_day
  ),
  line_agg as (
    select
      ord2.eff_day as day,
      sum(l.quantity) as items_sold,
      sum(case when ord2.outcome = 'delivered' then coalesce(l.revenue,0) else 0 end) as revenue,
      sum(case when ord2.outcome = 'delivered'
               then coalesce(l.cost_of_goods,0) - coalesce(l.refund_adjustment,0) - coalesce(l.damage_adjustment,0)
               else 0 end) as cogs,
      sum(coalesce(l.revenue,0)) as gross_revenue,
      sum(coalesce(l.cost_of_goods,0)) as gross_cogs,
      sum(coalesce(l.packing_cost,0)) as packaging,
      sum(case when ord2.outcome = 'failed_rto'
               then coalesce(l.allocated_courier_fee,0) + coalesce(l.allocated_open_package_fee,0)
               else 0 end) as bosta_penalty,
      sum(case when ord2.outcome is distinct from 'failed_rto'
               then coalesce(l.allocated_courier_fee,0) + coalesce(l.allocated_open_package_fee,0) + coalesce(l.allocated_cod_cash_fee,0)
               else 0 end) as bosta_fees_paid
    from ord2
    join public.order_line_items l on l.order_id = ord2.id
    group by ord2.eff_day
  )
  select
    coalesce(oa.day, la.day) as day,
    coalesce(oa.orders_placed, 0),
    coalesce(oa.orders_resolved, 0),
    coalesce(oa.delivered_count, 0),
    coalesce(la.items_sold, 0),
    coalesce(la.revenue, 0),
    coalesce(la.cogs, 0),
    coalesce(la.gross_revenue, 0),
    coalesce(la.gross_cogs, 0),
    coalesce(la.packaging, 0),
    coalesce(la.bosta_penalty, 0),
    coalesce(la.bosta_fees_paid, 0),
    coalesce(oa.shipping_fee_charged, 0)
  from order_agg oa
  full outer join line_agg la on oa.day = la.day;
$$;

notify pgrst, 'reload schema';


-- ===================== 0036_next_day_fee.sql =====================

-- Break the COD cash fee ("Next Day fee" - Bosta's 1% next-day cash-settlement
-- charge) out of bosta_fees_paid into its own cod_cash_fee column, so the
-- Income Statement can show it as a separate line instead of folding it into
-- Shipping Differences.
drop function if exists public.daily_pnl(text);
create or replace function public.daily_pnl(p_mode text)
returns table (
  day date,
  orders_placed bigint,
  orders_resolved bigint,
  delivered_count bigint,
  items_sold bigint,
  revenue numeric,
  cogs numeric,
  gross_revenue numeric,
  gross_cogs numeric,
  packaging numeric,
  bosta_penalty numeric,
  bosta_fees_paid numeric,
  cod_cash_fee numeric,
  shipping_fee_charged numeric
)
language sql
stable
as $$
  with ord as (
    select
      o.id,
      case
        when p_mode = 'performance' then o.egypt_day
        when o.outcome = 'delivered' then o.egypt_day  -- actual: delivered orders only, dated by order day
        else null
      end as eff_day,
      o.outcome,
      o.shipping_fee_charged
    from public.orders o
    where o.cancelled_at is null
  ),
  ord2 as (select * from ord where eff_day is not null),
  order_agg as (
    select
      eff_day as day,
      count(*) as orders_placed,
      count(*) filter (where outcome in ('delivered','failed_rto','exchange','pickup_return')) as orders_resolved,
      count(*) filter (where outcome = 'delivered') as delivered_count,
      sum(case when outcome is distinct from 'failed_rto' then coalesce(shipping_fee_charged,0) else 0 end) as shipping_fee_charged
    from ord2
    group by eff_day
  ),
  line_agg as (
    select
      ord2.eff_day as day,
      sum(l.quantity) as items_sold,
      sum(case when ord2.outcome = 'delivered' then coalesce(l.revenue,0) else 0 end) as revenue,
      sum(case when ord2.outcome = 'delivered'
               then coalesce(l.cost_of_goods,0) - coalesce(l.refund_adjustment,0) - coalesce(l.damage_adjustment,0)
               else 0 end) as cogs,
      sum(coalesce(l.revenue,0)) as gross_revenue,
      sum(coalesce(l.cost_of_goods,0)) as gross_cogs,
      sum(coalesce(l.packing_cost,0)) as packaging,
      sum(case when ord2.outcome = 'failed_rto'
               then coalesce(l.allocated_courier_fee,0) + coalesce(l.allocated_open_package_fee,0)
               else 0 end) as bosta_penalty,
      -- Courier + open-package on the non-returned side (COD cash fee split out below).
      sum(case when ord2.outcome is distinct from 'failed_rto'
               then coalesce(l.allocated_courier_fee,0) + coalesce(l.allocated_open_package_fee,0)
               else 0 end) as bosta_fees_paid,
      sum(case when ord2.outcome is distinct from 'failed_rto'
               then coalesce(l.allocated_cod_cash_fee,0)
               else 0 end) as cod_cash_fee
    from ord2
    join public.order_line_items l on l.order_id = ord2.id
    group by ord2.eff_day
  )
  select
    coalesce(oa.day, la.day) as day,
    coalesce(oa.orders_placed, 0),
    coalesce(oa.orders_resolved, 0),
    coalesce(oa.delivered_count, 0),
    coalesce(la.items_sold, 0),
    coalesce(la.revenue, 0),
    coalesce(la.cogs, 0),
    coalesce(la.gross_revenue, 0),
    coalesce(la.gross_cogs, 0),
    coalesce(la.packaging, 0),
    coalesce(la.bosta_penalty, 0),
    coalesce(la.bosta_fees_paid, 0),
    coalesce(la.cod_cash_fee, 0),
    coalesce(oa.shipping_fee_charged, 0)
  from order_agg oa
  full outer join line_agg la on oa.day = la.day;
$$;

grant execute on function public.daily_pnl(text) to anon, authenticated, service_role;

notify pgrst, 'reload schema';


-- ===================== 0037_expense_recording.sql =====================

-- Expense recording ledger + open-month assumptions. Replaces the hardcoded
-- fixed monthly expenses going forward (Jul 2026+): closed calendar months read
-- their recorded actuals, the current month reads the Settings assumption, and
-- months before the cutover keep the hardcoded MIRAJ figures (in code).

create table if not exists public.expense_accounts (
  id bigint generated always as identity primary key,
  name text not null unique,
  kind text not null check (kind in ('income', 'expense')),
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

insert into public.expense_accounts (name, kind, sort_order) values
  ('Salary', 'expense', 1),
  ('Post Production', 'expense', 2),
  ('Subscription', 'expense', 3),
  ('Rent', 'expense', 4),
  ('Transportation', 'expense', 5),
  ('Other', 'expense', 6),
  ('Bosta', 'income', 7)
on conflict (name) do nothing;

-- Actual recorded entries (amount is always positive; income vs expense comes
-- from the account's kind).
create table if not exists public.expense_entries (
  id bigint generated always as identity primary key,
  date date not null,
  account_id bigint not null references public.expense_accounts(id),
  amount numeric(12,2) not null check (amount > 0),
  note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists expense_entries_date_idx on public.expense_entries (date);
create index if not exists expense_entries_account_idx on public.expense_entries (account_id);

-- One monthly assumption per expense account, used for the current (open)
-- calendar month.
create table if not exists public.expense_assumptions (
  account_id bigint primary key references public.expense_accounts(id),
  monthly_amount numeric(12,2) not null default 0,
  updated_at timestamptz not null default now()
);

notify pgrst, 'reload schema';


-- ===================== 0038_open_package_line.sql =====================

-- Break the open-package fee (7 EGP + 14% VAT, charged on every order whatever
-- the outcome) out of bosta_fees_paid / bosta_penalty into its own
-- open_package_fee column, so the Income Statement can show it as its own line.
-- Net Income is unchanged - it was already subtracted, just bundled.
drop function if exists public.daily_pnl(text);
create or replace function public.daily_pnl(p_mode text)
returns table (
  day date,
  orders_placed bigint,
  orders_resolved bigint,
  delivered_count bigint,
  items_sold bigint,
  revenue numeric,
  cogs numeric,
  gross_revenue numeric,
  gross_cogs numeric,
  packaging numeric,
  bosta_penalty numeric,
  bosta_fees_paid numeric,
  cod_cash_fee numeric,
  open_package_fee numeric,
  shipping_fee_charged numeric
)
language sql
stable
as $$
  with ord as (
    select
      o.id,
      case
        when p_mode = 'performance' then o.egypt_day
        when o.outcome = 'delivered' then o.egypt_day
        else null
      end as eff_day,
      o.outcome,
      o.shipping_fee_charged
    from public.orders o
    where o.cancelled_at is null
  ),
  ord2 as (select * from ord where eff_day is not null),
  order_agg as (
    select
      eff_day as day,
      count(*) as orders_placed,
      count(*) filter (where outcome in ('delivered','failed_rto','exchange','pickup_return')) as orders_resolved,
      count(*) filter (where outcome = 'delivered') as delivered_count,
      sum(case when outcome is distinct from 'failed_rto' then coalesce(shipping_fee_charged,0) else 0 end) as shipping_fee_charged
    from ord2
    group by eff_day
  ),
  line_agg as (
    select
      ord2.eff_day as day,
      sum(l.quantity) as items_sold,
      sum(case when ord2.outcome = 'delivered' then coalesce(l.revenue,0) else 0 end) as revenue,
      sum(case when ord2.outcome = 'delivered'
               then coalesce(l.cost_of_goods,0) - coalesce(l.refund_adjustment,0) - coalesce(l.damage_adjustment,0)
               else 0 end) as cogs,
      sum(coalesce(l.revenue,0)) as gross_revenue,
      sum(coalesce(l.cost_of_goods,0)) as gross_cogs,
      sum(coalesce(l.packing_cost,0)) as packaging,
      -- Courier fee only (open package split out below).
      sum(case when ord2.outcome = 'failed_rto' then coalesce(l.allocated_courier_fee,0) else 0 end) as bosta_penalty,
      sum(case when ord2.outcome is distinct from 'failed_rto' then coalesce(l.allocated_courier_fee,0) else 0 end) as bosta_fees_paid,
      sum(case when ord2.outcome is distinct from 'failed_rto' then coalesce(l.allocated_cod_cash_fee,0) else 0 end) as cod_cash_fee,
      -- Open package fee on every order (any outcome).
      sum(coalesce(l.allocated_open_package_fee,0)) as open_package_fee
    from ord2
    join public.order_line_items l on l.order_id = ord2.id
    group by ord2.eff_day
  )
  select
    coalesce(oa.day, la.day) as day,
    coalesce(oa.orders_placed, 0),
    coalesce(oa.orders_resolved, 0),
    coalesce(oa.delivered_count, 0),
    coalesce(la.items_sold, 0),
    coalesce(la.revenue, 0),
    coalesce(la.cogs, 0),
    coalesce(la.gross_revenue, 0),
    coalesce(la.gross_cogs, 0),
    coalesce(la.packaging, 0),
    coalesce(la.bosta_penalty, 0),
    coalesce(la.bosta_fees_paid, 0),
    coalesce(la.cod_cash_fee, 0),
    coalesce(la.open_package_fee, 0),
    coalesce(oa.shipping_fee_charged, 0)
  from order_agg oa
  full outer join line_agg la on oa.day = la.day;
$$;

grant execute on function public.daily_pnl(text) to anon, authenticated, service_role;
notify pgrst, 'reload schema';


-- ===================== 0039_actual_pickup_day_basis.sql =====================

-- Actual mode buckets on the day the package was handed to the courier, not
-- the Shopify order day. This restores the original intent of migration 0026:
-- Shopify auto-forwards every order to Bosta the instant it's placed (leg state
-- "Created"), but the owner may not hand the physical package over for days
-- (observed: ordered Jun 28, collected by Bosta Jul 13 - median lag 1 day, max
-- 31), so the order day says nothing about when an order actually shipped.
--
-- Why this was broken: the 0027/0028 backfills were gated on `courier =
-- 'bosta'`, but courier is owner-entered from the Shipping Orders tab and is
-- NULL on every Miraj order - so both matched zero rows, bosta_picked_up_day
-- stayed null forever, and 0035 concluded the pickup basis "made Actual empty"
-- and fell back to dating delivered orders by their order day. That made Actual
-- a near-copy of Performance: same revenue by construction (revenue is
-- delivered-only in BOTH modes), and byte-identical in the still-open month.
--
-- Part 1 re-runs the 0028 backfill without the courier gate. Part 2 repoints the
-- aggregate at bosta_picked_up_day. Going forward the Bosta sync maintains the
-- column itself (see pickedUpDay() in src/lib/sync/bosta-deliveries.ts).
--
-- NOTE: part 2 is based on the function as it exists in the live database, which
-- is 0036's 14-column shape (day..cod_cash_fee, shipping_fee_charged) - NOT the
-- 15-column 0038 shape, since 0038 was never applied here. Only the eff_day CASE
-- differs from the live definition; every other expression is byte-identical, so
-- this changes which day/orders each mode sees and nothing else. Keep the
-- signature in sync with whatever is live or `create or replace` will fail with
-- "cannot change return type of existing function".

-- Part 1: backfill bosta_picked_up_day from data already in bosta_events.
-- Earliest collectedFromBusiness across all non-"Created" legs (Bosta mutates a
-- leg's type in place on RTO/Exchange, so this cannot filter on type 'Send';
-- earliest so a genuine second shipment never overrides the original pickup).
-- +3 hours = the fixed UTC+3 Egypt offset used for egypt_day everywhere else.
update public.orders o
set bosta_picked_up_day = (be.collected_from_business + interval '3 hours')::date
from (
  select order_id, min((raw_payload->>'collectedFromBusiness')::timestamptz) as collected_from_business
  from public.bosta_events
  where bosta_state <> 'Created'
    and raw_payload->>'collectedFromBusiness' is not null
  group by order_id
) be
where be.order_id = o.id
  and o.bosta_picked_up_day is null;

-- Part 2: Actual = orders handed to a courier, dated by that handover day.
-- Orders never handed over (no pickup date on either courier) are excluded
-- entirely - an order Shopify auto-forwarded but that never physically shipped
-- has no place in a fulfillment view. Performance mode is unchanged.
--
-- Dropped first: changing the OUT columns of an existing function is a 42P13
-- error, not a replace. See the same note in 0035.
drop function if exists public.daily_pnl(text);
create or replace function public.daily_pnl(p_mode text)
returns table (
  day date,
  orders_placed bigint,
  orders_resolved bigint,
  delivered_count bigint,
  items_sold bigint,
  revenue numeric,
  cogs numeric,
  gross_revenue numeric,
  gross_cogs numeric,
  packaging numeric,
  bosta_penalty numeric,
  bosta_fees_paid numeric,
  cod_cash_fee numeric,
  shipping_fee_charged numeric
)
language sql
stable
as $$
  with ord as (
    select
      o.id,
      case
        when p_mode = 'performance' then o.egypt_day
        else coalesce(o.bosta_picked_up_day, o.movers_record_date)  -- actual: courier handover day
      end as eff_day,
      o.outcome,
      o.shipping_fee_charged
    from public.orders o
    where o.cancelled_at is null
  ),
  ord2 as (select * from ord where eff_day is not null),
  order_agg as (
    select
      eff_day as day,
      count(*) as orders_placed,
      count(*) filter (where outcome in ('delivered','failed_rto','exchange','pickup_return')) as orders_resolved,
      count(*) filter (where outcome = 'delivered') as delivered_count,
      sum(case when outcome is distinct from 'failed_rto' then coalesce(shipping_fee_charged,0) else 0 end) as shipping_fee_charged
    from ord2
    group by eff_day
  ),
  line_agg as (
    select
      ord2.eff_day as day,
      sum(l.quantity) as items_sold,
      sum(case when ord2.outcome = 'delivered' then coalesce(l.revenue,0) else 0 end) as revenue,
      sum(case when ord2.outcome = 'delivered'
               then coalesce(l.cost_of_goods,0) - coalesce(l.refund_adjustment,0) - coalesce(l.damage_adjustment,0)
               else 0 end) as cogs,
      sum(coalesce(l.revenue,0)) as gross_revenue,
      sum(coalesce(l.cost_of_goods,0)) as gross_cogs,
      sum(coalesce(l.packing_cost,0)) as packaging,
      sum(case when ord2.outcome = 'failed_rto'
               then coalesce(l.allocated_courier_fee,0) + coalesce(l.allocated_open_package_fee,0)
               else 0 end) as bosta_penalty,
      -- Courier + open-package on the non-returned side (COD cash fee split out below).
      sum(case when ord2.outcome is distinct from 'failed_rto'
               then coalesce(l.allocated_courier_fee,0) + coalesce(l.allocated_open_package_fee,0)
               else 0 end) as bosta_fees_paid,
      sum(case when ord2.outcome is distinct from 'failed_rto'
               then coalesce(l.allocated_cod_cash_fee,0)
               else 0 end) as cod_cash_fee
    from ord2
    join public.order_line_items l on l.order_id = ord2.id
    group by ord2.eff_day
  )
  select
    coalesce(oa.day, la.day) as day,
    coalesce(oa.orders_placed, 0),
    coalesce(oa.orders_resolved, 0),
    coalesce(oa.delivered_count, 0),
    coalesce(la.items_sold, 0),
    coalesce(la.revenue, 0),
    coalesce(la.cogs, 0),
    coalesce(la.gross_revenue, 0),
    coalesce(la.gross_cogs, 0),
    coalesce(la.packaging, 0),
    coalesce(la.bosta_penalty, 0),
    coalesce(la.bosta_fees_paid, 0),
    coalesce(la.cod_cash_fee, 0),
    coalesce(oa.shipping_fee_charged, 0)
  from order_agg oa
  full outer join line_agg la on oa.day = la.day;
$$;

notify pgrst, 'reload schema';


-- ===================== 0040_final_product_bom.sql =====================

-- Product List: switch from the base-cost + packaging cost model to the
-- bill-of-materials model (mirrors the Laurel dashboard's Product List).
--
--   product_components        - the raw materials / packaging / stickers /
--                               other inputs, each priced per unit (pcs/L/KG).
--   final_product_components  - a single product's BOM: which components (and
--                               how much of each) it is built from.
--   bundle_items (extended)   - a bundle's contents: member single products
--                               AND/OR "Other" components (e.g. the box).
--
-- A product's built cost (single = Σ component line costs, bundle = Σ contents)
-- feeds the margin engine via getBuiltCostByProduct(). is_bundle already exists
-- from 0034. The old packaging_types / product_packaging / products.base_cost
-- objects are left in place but are no longer read by the app.

-- Components catalog. Kept in sync with COMPONENT_TYPES / COMPONENT_UNITS in
-- src/lib/products/component-types.ts.
create table if not exists public.product_components (
  id bigint generated always as identity primary key,
  type text not null check (type in ('raw_material', 'product_package', 'sticker', 'other')),
  account text not null,
  unit text not null check (unit in ('pcs', 'l', 'kg')),
  cost numeric(12, 2),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists product_components_type_idx on public.product_components (type);

-- Bill of materials: single products -> the components they are built from.
create table if not exists public.final_product_components (
  id bigint generated always as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  component_id bigint not null references public.product_components(id) on delete cascade,
  quantity numeric(12, 3) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (product_id, component_id)
);
create index if not exists final_product_components_product_idx on public.final_product_components (product_id);
create index if not exists final_product_components_component_idx on public.final_product_components (component_id);

-- Extend bundle_items so a bundle row references EXACTLY ONE of a member single
-- product OR an "Other" component (the box). Was: composite PK
-- (bundle_product_id, member_product_id), member NOT NULL. Existing member rows
-- are preserved. Guarded so re-running is a no-op.
do $$
begin
  -- Drop the old composite primary key so member_product_id can become nullable.
  if exists (
    select 1 from pg_constraint
    where conrelid = 'public.bundle_items'::regclass and conname = 'bundle_items_pkey'
  ) then
    alter table public.bundle_items drop constraint bundle_items_pkey;
  end if;

  -- Surrogate id primary key (fills existing rows).
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'bundle_items' and column_name = 'id'
  ) then
    alter table public.bundle_items add column id bigint generated always as identity primary key;
  end if;

  -- component_id: the "Other" component alternative to a member product.
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'bundle_items' and column_name = 'component_id'
  ) then
    alter table public.bundle_items
      add column component_id bigint references public.product_components(id) on delete cascade;
  end if;
end $$;

alter table public.bundle_items alter column member_product_id drop not null;
alter table public.bundle_items drop constraint if exists bundle_not_self;
alter table public.bundle_items drop constraint if exists bundle_items_exactly_one_ref;
alter table public.bundle_items
  add constraint bundle_items_exactly_one_ref
    check ((member_product_id is not null)::int + (component_id is not null)::int = 1);

-- Re-establish uniqueness now that the composite PK is gone (these back the
-- app's upserts on (bundle_product_id, member_product_id) and (…, component_id)).
create unique index if not exists bundle_items_bundle_member_key
  on public.bundle_items (bundle_product_id, member_product_id);
create unique index if not exists bundle_items_bundle_component_key
  on public.bundle_items (bundle_product_id, component_id);

notify pgrst, 'reload schema';


-- ===================== 0041_product_variants.sql =====================

-- Variant-level costing. Until now `products` held one row per SHOPIFY PRODUCT
-- and the catalog sync read variants(first: 1), so a product sold in several
-- sizes (e.g. رطب سكري القصيم in 1 kilo and 3 kilo) collapsed into a single row
-- with a single BOM and a single built cost.
--
--   product_variants                  - one row per Shopify variant.
--   final_product_components.variant_id - a BOM row now hangs off EITHER the
--                                       product (variant_id null = applies to
--                                       every variant) OR one specific variant.
--   order_line_items.variant_id       - which variant a sale was actually for,
--                                       so margins use that variant's cost.
--
-- Products with one variant keep working exactly as before: the sync still
-- writes their sku/price onto products, and their BOM rows stay variant_id null.

create table if not exists public.product_variants (
  id bigint generated always as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  shopify_variant_id bigint not null unique,
  title text not null,
  sku text,
  current_price numeric(12, 2),
  position int not null default 1,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists product_variants_product_idx on public.product_variants (product_id);

-- BOM rows: product-level (variant_id null) or variant-specific.
alter table public.final_product_components
  add column if not exists variant_id bigint references public.product_variants(id) on delete cascade;

-- The old unique (product_id, component_id) would block the same component
-- appearing on two variants of one product, so replace it with a pair of
-- partial indexes (Postgres treats NULLs as distinct in a plain unique index,
-- which is exactly the wrong behaviour for the product-level rows).
alter table public.final_product_components
  drop constraint if exists final_product_components_product_id_component_id_key;
create unique index if not exists final_product_components_product_component_key
  on public.final_product_components (product_id, component_id)
  where variant_id is null;
create unique index if not exists final_product_components_variant_component_key
  on public.final_product_components (variant_id, component_id)
  where variant_id is not null;
create index if not exists final_product_components_variant_idx
  on public.final_product_components (variant_id);

-- Which variant each sale was for. shopify_variant_id is captured by the orders
-- sync even when the variant row doesn't exist yet, so the catalog sync can
-- relink it later (same pattern as shopify_product_id in 0029).
alter table public.order_line_items add column if not exists shopify_variant_id bigint;
alter table public.order_line_items
  add column if not exists variant_id bigint references public.product_variants(id);
create index if not exists order_line_items_variant_id_idx on public.order_line_items (variant_id);

notify pgrst, 'reload schema';


-- ===================== 0042_bundle_items_variant.sql =====================

-- Let a bundle contain a specific VARIANT of a product, not just a whole
-- product. After 0041 a multi-variant product (e.g. رطب سكري القصيم in 1 kilo
-- and 3 kilo) has a different cost per variant, so "5 boxes of the 1 kilo"
-- can't be expressed by pointing at the product alone.
--
-- bundle_items now references EXACTLY ONE of:
--   member_product_id  - a whole single product (unchanged, existing rows)
--   member_variant_id  - one variant of a single product
--   component_id       - an "Other" component (the box)

alter table public.bundle_items
  add column if not exists member_variant_id bigint references public.product_variants(id) on delete cascade;

alter table public.bundle_items drop constraint if exists bundle_items_exactly_one_ref;
alter table public.bundle_items
  add constraint bundle_items_exactly_one_ref
    check (
      (member_product_id is not null)::int
      + (member_variant_id is not null)::int
      + (component_id is not null)::int = 1
    );

-- Backs the app's upsert on (bundle_product_id, member_variant_id), matching
-- the existing member/component unique indexes from 0040.
create unique index if not exists bundle_items_bundle_variant_key
  on public.bundle_items (bundle_product_id, member_variant_id);

notify pgrst, 'reload schema';


-- ===================== 0043_variant_only_bom.sql =====================

-- Multi-variant products are costed BY VARIANT ONLY. Until now a product-level
-- BOM row (variant_id null) acted as the default every variant inherited; with
-- the Final Product tab no longer offering a product-level editor for these
-- products, such rows would be stranded - invisible but still feeding cost.
--
-- So push each product-level row down onto every variant that doesn't already
-- have that component (preserving the exact cost each variant was inheriting),
-- then drop the product-level rows for multi-variant products only.
--
-- Single-variant products are untouched: they keep costing at the product level
-- exactly as before.

with multi as (
  select product_id from public.product_variants group by product_id having count(*) > 1
)
insert into public.final_product_components (product_id, component_id, variant_id, quantity)
select f.product_id, f.component_id, v.id, f.quantity
from public.final_product_components f
join multi m on m.product_id = f.product_id
join public.product_variants v on v.product_id = f.product_id
where f.variant_id is null
  and not exists (
    select 1 from public.final_product_components existing
    where existing.variant_id = v.id and existing.component_id = f.component_id
  );

delete from public.final_product_components f
using (select product_id from public.product_variants group by product_id having count(*) > 1) m
where f.product_id = m.product_id and f.variant_id is null;

notify pgrst, 'reload schema';


-- ===================== 0044_bundle_fractional_quantity.sql =====================

-- Bundle contents can hold a FRACTION of an item (0.5 of a raw material, 0.8 of
-- a member product), not just whole counts. quantity was numeric(12,2) while the
-- single-product BOM (final_product_components) is numeric(12,3) and both UIs
-- offer step="0.001" - so a third decimal silently rounded here. Match the BOM.
alter table public.bundle_items alter column quantity type numeric(12, 3);

notify pgrst, 'reload schema';


-- ===================== 0045_per_product_stats_variant.sql =====================

-- Analysis by Product aggregates on product_id only, so a product sold in
-- several variants (each with its own price AND its own cost since 0041) shows
-- as one blended row. Add variant_id to the grouping so the report can break a
-- product down by variant.
--
-- variant_id is NULL for single-variant products and for old lines whose
-- Shopify variant was later deleted; the app treats a NULL group as the
-- product-level row, so nothing is dropped and totals are unchanged.

drop function if exists public.per_product_stats(text, date, date);
create or replace function public.per_product_stats(p_mode text, p_from date, p_to date)
returns table (
  product_id bigint,
  variant_id bigint,
  orders_placed bigint,
  orders_resolved bigint,
  items_sold bigint,
  revenue numeric,
  cogs numeric
)
language sql
stable
as $$
  with ord as (
    select
      o.id,
      case
        when p_mode = 'performance' then o.egypt_day
        when o.courier = 'movers' then o.movers_record_date
        when o.courier = 'bosta' then o.bosta_picked_up_day
        else null
      end as eff_day,
      o.outcome
    from public.orders o
    where o.cancelled_at is null
  ),
  ord2 as (
    select * from ord where eff_day is not null and eff_day >= p_from and eff_day <= p_to
  )
  select
    l.product_id,
    l.variant_id,
    count(*) as orders_placed,
    count(*) filter (where ord2.outcome in ('delivered','failed_rto','exchange','pickup_return')) as orders_resolved,
    sum(coalesce(l.quantity, 0)) as items_sold,
    sum(coalesce(l.revenue, 0)) as revenue,
    sum(coalesce(l.cost_of_goods, 0)) as cogs
  from ord2
  join public.order_line_items l on l.order_id = ord2.id
  where l.product_id is not null
  group by l.product_id, l.variant_id;
$$;

grant execute on function public.per_product_stats(text, date, date) to anon, authenticated, service_role;

notify pgrst, 'reload schema';


-- ===================== 0046_ad_spend_general.sql =====================

-- "General" ad spend: brand/general campaigns that don't promote one model and
-- should be spread across all of them.
--
-- This can NOT be represented as model_group_id = null, because null already
-- means "not allocated yet" - it's exactly what the allocation popup lists
-- (getUnmappedAds). A general ad marked that way would reappear in the popup
-- forever. Hence an explicit flag.

alter table public.ad_spend add column if not exists is_general boolean not null default false;
create index if not exists ad_spend_is_general_idx on public.ad_spend (is_general) where is_general;

-- The ad_id -> model mapping now records a general choice too, so the Meta sync
-- re-applies it to future days for that ad (same as a model assignment).
alter table public.ad_model_assignments add column if not exists is_general boolean not null default false;
alter table public.ad_model_assignments alter column model_group_id drop not null;
alter table public.ad_model_assignments drop constraint if exists ad_model_assignments_target_check;
alter table public.ad_model_assignments
  add constraint ad_model_assignments_target_check
    check ((model_group_id is not null) <> is_general);

notify pgrst, 'reload schema';


-- ===================== 0047_analysis_only_accounts.sql =====================

-- Analysis-only expense accounts: categories the owner wants to track and see
-- in the Expense Analysis report, but that must NOT reduce Net Income on the
-- Income Statement (e.g. owner drawings, one-off non-operating spend).
--
-- The Income Statement only ever reads the six fixed overhead accounts (Salary,
-- Post Production, Subscription, Rent, Transportation, Other) via ACCOUNT_TO_KEY
-- in expenses-ledger.ts, so any other account is already excluded from the P&L.
-- This flag makes that intent explicit and drives the Expense Analysis, which
-- shows in_income_statement = false accounts as their own rows.

alter table public.expense_accounts
  add column if not exists in_income_statement boolean not null default true;

notify pgrst, 'reload schema';


-- ===================== 0048_chat_orders.sql =====================

-- "Chat Orders": orders taken over chat and fulfilled directly, recorded by hand
-- in the Bosta → Chat Orders tab. Nothing syncs them and no courier is ever
-- involved, so they are always 100% delivered - which is why they carry no
-- outcome/return columns.
--
-- Ported from Laurel (its 0052_chat_orders.sql), with one Miraj-specific
-- addition: variant_id. Laurel has no variant concept, but in Miraj a product
-- with MORE THAN ONE variant is costed BY VARIANT ONLY (see 0041/0043) and is
-- deliberately absent from getBuiltCosts().byProduct - so recording such a sale
-- against the bare product would price it at 0. Multi-variant products are
-- therefore offered (and stored) as variants, exactly like the bundle picker.
--
-- Revenue is ONE owner-typed figure for the whole order (the price agreed in the
-- chat), NOT a sum over the line items - which is why it lives on the order and
-- not the items. The items exist only to price COGS.
create table if not exists public.chat_orders (
  id bigint generated always as identity primary key,
  sale_date date not null,
  revenue numeric(12, 2) not null check (revenue >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists chat_orders_date_idx on public.chat_orders (sale_date);

-- cost_of_goods is snapshotted at write time from the product's (or variant's)
-- built cost, so a later BOM change can't silently rewrite an already-recorded
-- order. Editing an order re-prices every item, since quantities may have moved.
--
-- NOTE vs Laurel: Laurel prices each line at the cost effective ON sale_date via
-- getBuiltCostResolver(), which reads a `purchases` cost timeline. Miraj has no
-- such table (final-products.ts deliberately omits that resolver), so lines are
-- priced at the CURRENT built cost instead. Backdating an order therefore prices
-- it at today's cost, not that day's.
create table if not exists public.chat_order_items (
  id bigint generated always as identity primary key,
  order_id bigint not null references public.chat_orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  -- Null for a single-variant product or a bundle; set for one variant of a
  -- multi-variant product.
  variant_id bigint references public.product_variants(id),
  quantity int not null check (quantity > 0),
  cost_of_goods numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);
create index if not exists chat_order_items_order_idx on public.chat_order_items (order_id);

notify pgrst, 'reload schema';


-- ===================== 0049_product_aliases.sql =====================

-- Arabic names for finished goods, learned from pasted WhatsApp orders.
--
-- The catalog name is often English or differently phrased, but chat orders
-- arrive in Arabic, so nothing can be matched by plain string comparison. This
-- table is the bridge: the Chat Orders paste box matches each product line
-- against these aliases, and every line the owner resolves by hand in the review
-- step is written back here - so the same phrasing matches itself next time. It
-- starts empty and fills up over the first days of use.
--
-- alias_norm is the matching key: the alias put through normalizeArabic() in
-- src/lib/chat-orders/whatsapp.ts (Arabic-Indic digits folded to ASCII,
-- diacritics and tatweel stripped, أإآ→ا ى→ي ة→ه, punctuation collapsed). It is
-- UNIQUE, so a phrase can only ever point at one product - re-teaching it
-- repoints it rather than creating a rival row. alias_text keeps the original
-- spelling for display.
--
-- Ported from Laurel (its 0055_product_aliases.sql) plus variant_id: in Miraj a
-- multi-variant product is costed per variant, so an alias has to resolve to the
-- exact variant that was sold, not just the parent product.
create table if not exists public.product_aliases (
  id bigint generated always as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  variant_id bigint references public.product_variants(id) on delete cascade,
  alias_norm text not null unique,
  alias_text text not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists product_aliases_product_idx on public.product_aliases (product_id);

notify pgrst, 'reload schema';


-- ===================== 0050_purchasing.sql =====================

-- Purchasing: record what was paid for a component or a finished product, on a
-- date, and let it drive that item's current cost.
--
-- A purchase targets EITHER a catalog component (raw material / package /
-- sticker / other - what is normally bought) OR a finished product. Exactly one
-- of component_id / product_id is set.
--
--   component -> product_components.cost is updated, and every product whose BOM
--                uses that component re-costs automatically through the rollup.
--   product   -> products.unit_cost_override is updated. Note this sits AHEAD of
--                the BOM in the engine (see margin.ts), so a product purchase
--                takes over from that product's bill of materials.
--
-- Costs are flat, not effective-dated: Miraj's built cost is a live rollup from
-- current component costs, so editing a cost already restates historical margins
-- once they recompute. Purchasing follows the same rule rather than pretending
-- to a precision the rollup doesn't have.
--
-- Both the total paid and the derived per-unit cost are stored, because neither
-- reproduces the other exactly: total_amount is what was actually paid and is
-- what posts to the ledger, while amount is total_amount / quantity rounded to
-- 2dp (the precision product_components.cost carries). Rebuilding the total as
-- quantity x amount would drift whenever the division isn't exact.

create table if not exists public.purchases (
  id bigint generated always as identity primary key,
  date date not null,
  component_id bigint references public.product_components(id) on delete cascade,
  product_id bigint references public.products(id) on delete cascade,
  -- Quantity in the target's PRICED unit (pcs / L / KG for a component, pieces
  -- for a product) - the same unit its cost is expressed per.
  quantity numeric(12,3) not null check (quantity > 0),
  amount numeric(12,2) not null check (amount >= 0),
  total_amount numeric(12,2) not null check (total_amount >= 0),
  expense_entry_id bigint references public.expense_entries(id) on delete set null,
  created_at timestamptz not null default now(),
  constraint purchases_one_target check (
    (component_id is not null and product_id is null) or
    (component_id is null and product_id is not null)
  )
);
create index if not exists purchases_component_idx on public.purchases (component_id, date);
create index if not exists purchases_product_idx on public.purchases (product_id, date);
create index if not exists purchases_date_idx on public.purchases (date);

grant all on public.purchases to anon, authenticated, service_role;

-- The account purchases post to. in_income_statement = false keeps it out of the
-- P&L - inventory is already deducted per delivered order as COGS, so posting
-- purchases there too would double-count - while still showing in Expense
-- Analysis as its own row.
insert into public.expense_accounts (name, kind, sort_order, in_income_statement)
select 'Purchasing', 'expense', coalesce(max(sort_order), 0) + 1, false
from public.expense_accounts
on conflict (name) do nothing;

notify pgrst, 'reload schema';


-- ===================== 0051_enable_rls.sql =====================

-- Row-level security for every table this project owns.
--
-- Miraj keeps its tables in its own schema, not public: src/lib/supabase.ts
-- sets db.schema from SUPABASE_SCHEMA=public. Two consequences worth stating,
-- because neither is obvious:
--
--   1. Supabase's rls_disabled_in_public advisor only inspects the public
--      schema, so this project never appeared in the security warning emails.
--      That means the advisor was not looking - not that the data was safe.
--   2. PostgREST serves miraj all the same (the app reaches it over the Data
--      API with the schema header; a request with Accept-Profile: miraj
--      returns rows), so with RLS off the anon key - a key designed to be handed
--      to browsers - could read, edit and delete every row.
--
-- Enabling RLS with NO policies denies anon and authenticated everything, which
-- is exactly right here: this app has no browser-side database access to
-- preserve. src/lib/supabase.ts is server-only and authenticates with the
-- service-role SUPABASE_SECRET_KEY, which carries BYPASSRLS, so every server
-- query keeps working untouched - the sync routes and scripts/*.mjs included.
-- If a table ever does need direct client reads, add a policy for it then;
-- until a policy exists the table is simply closed.
--
-- Covers public too. It looks empty on this project (a request for public.orders
-- returns nothing), but this codebase was forked from Laundor and several early
-- migrations still carry unqualified or laundor-qualified creates, so anything
-- that did land in public gets closed rather than left behind. A loop, not a
-- hand-listed set, for the same reason: the catalog is the only reliable record
-- of what actually exists here.
do $$
declare
  t record;
begin
  for t in
    select schemaname, tablename
    from pg_tables
    where schemaname in ('public', 'public')
    order by schemaname, tablename
  loop
    execute format('alter table %I.%I enable row level security', t.schemaname, t.tablename);
    raise notice 'RLS enabled on %.%', t.schemaname, t.tablename;
  end loop;
end
$$;

-- Verification - every row should read rowsecurity = true:
--   select schemaname, tablename, rowsecurity from pg_tables
--   where schemaname in ('public', 'public') order by schemaname, tablename;


-- ===================== 0052_chat_order_count.sql =====================

-- A single chat_orders row can stand for MORE THAN ONE real order. The owner
-- sometimes bundles several chats into one record (e.g. 10 orders typed as one).
-- Revenue, COGS and items are already the bundle's totals, so those need no
-- scaling - but the Shipping Difference is a PER-ORDER figure (see
-- src/lib/reports/daily-pnl.ts), so reporting has to know how many real orders a
-- row represents to estimate it. Defaults to 1 - one row, one order - which is
-- exactly how every existing record and every future single-order record behaves.
alter table public.chat_orders
  add column if not exists order_count int not null default 1 check (order_count > 0);

notify pgrst, 'reload schema';


-- ===================== 0053_bosta_rate_card_2026_08_04.sql =====================

-- Bosta's rate card changed on 2026-08-04: new (lower) VAT-inclusive delivery
-- fees per governorate, and the open-package handling fee is closed from that
-- date. The "Next Day" COD cash-settlement fee is NOT closed here - Miraj
-- still pays it (this is where this business differs from O Garage, which
-- closed both on the same date).
--
-- None of this could be expressed before. bosta_fee_matrix held exactly one
-- rate per (zone, size), and the two add-ons were single columns on settings, so
-- editing any of them rewrote already-reported history: margin.ts recomputes a
-- rolling window that still reaches back into June. Both now carry an
-- effective_from and are read as-of each order's own egypt_day.
--
-- This is deliberately a different rule from product costs, which 0050 keeps
-- flat on purpose (the built cost is a live BOM rollup, so it cannot pretend to
-- be effective-dated). A courier rate card is not a rollup - it genuinely
-- changes on a date and both sides of that date are correct, so it is dated.
--
-- The pre-2026-08-04 rows below are the rates that were live until now, seeded
-- verbatim from the existing table/settings, so historical margins recompute to
-- exactly the numbers already reported.

-- 1. Effective-date the zone x size grid ------------------------------------
alter table public.bosta_fee_matrix
  add column if not exists effective_from date not null default date '2000-01-01';

alter table public.bosta_fee_matrix drop constraint if exists bosta_fee_matrix_pkey;
alter table public.bosta_fee_matrix
  add constraint bosta_fee_matrix_pkey primary key (zone, shipment_size, effective_from);

-- 2. Effective-date the two flat add-ons ------------------------------------
-- One row per pricing period. They are separate columns because Bosta prices
-- them separately - as this very change shows, one can close while the other
-- carries on.
create table if not exists public.bosta_fee_periods (
  effective_from date primary key,
  -- Flat per-shipment "open package" handling fee, charged whatever the
  -- outcome. Stored ex-VAT (unlike the matrix, which is VAT-inclusive), so
  -- readers gross it up by open_package_vat_pct.
  open_package_fee numeric(12,2) not null,
  open_package_vat_pct numeric(6,4) not null,
  -- "Next Day" cash-settlement fee, as a fraction of COD collected.
  cod_cash_fee_pct numeric(6,4) not null,
  note text,
  created_at timestamptz not null default now()
);

alter table public.bosta_fee_periods enable row level security;

-- Opening period carries whatever settings holds right now (7.00 + 14% VAT,
-- 1% COD), read from the table rather than hardcoded so this can't drift.
insert into public.bosta_fee_periods (effective_from, open_package_fee, open_package_vat_pct, cod_cash_fee_pct, note)
select date '2000-01-01', s.bosta_open_package_fee, s.bosta_open_package_vat_pct, s.cod_cash_fee_pct,
       'Opening period - migrated from settings'
from public.settings s where s.id = 1
on conflict (effective_from) do nothing;

-- Open package closed; the next-day fee carries over unchanged, again read from
-- settings so this period cannot silently diverge from what was in force.
insert into public.bosta_fee_periods (effective_from, open_package_fee, open_package_vat_pct, cod_cash_fee_pct, note)
select date '2026-08-04', 0, 0, s.cod_cash_fee_pct,
       'Open-package fee closed; Next Day fee still charged'
from public.settings s where s.id = 1
on conflict (effective_from) do nothing;

-- settings is no longer the source of truth for these three - drop them rather
-- than leave a second, silently-stale copy (the way vat_multiplier was left
-- behind by 0005 and has been dead ever since).
alter table public.settings drop column if exists bosta_open_package_fee;
alter table public.settings drop column if exists bosta_open_package_vat_pct;
alter table public.settings drop column if exists cod_cash_fee_pct;

-- 3. Helwan becomes its own zone --------------------------------------------
-- The new card prices Helwan at 108 while Cairo is 93, so it can no longer be
-- folded into Cairo (src/lib/governorates.ts drops that alias in the same
-- change). Its pre-2026-08-04 rates are Cairo's, so orders that previously
-- resolved to Cairo through the alias keep costing exactly what they did.
insert into public.governorate_fees (governorate, zone, updated_at)
values ('Helwan', 'Helwan', now())
on conflict (governorate) do update set zone = excluded.zone, updated_at = now();

insert into public.bosta_fee_matrix
  (zone, shipment_size, effective_from, deliver, exchange, return_pickup, cash_collection, return_to_origin)
values ('Helwan', 'Small & Medium', date '2000-01-01', 104.88, 0, 0, 0, 99.18)
on conflict (zone, shipment_size, effective_from) do nothing;

-- 4. The new card, effective 2026-08-04 -------------------------------------
-- Fees as given by the owner, already VAT-inclusive (same basis as the existing
-- rows). Return-to-origin keeps the rule the existing card already follows
-- exactly: delivery fee - 5.70 (5 EGP + 14% VAT), confirmed unchanged.
insert into public.bosta_fee_matrix
  (zone, shipment_size, effective_from, deliver, exchange, return_pickup, cash_collection, return_to_origin)
select v.zone, 'Small & Medium', date '2026-08-04', v.deliver, 0, 0, 0, v.deliver - 5.70
from (values
  ('Cairo', 93.00), ('Giza', 93.00),
  ('Alexandria', 101.00), ('Beheira', 101.00),
  ('Dakahlia', 108.00), ('Qalyubia', 108.00), ('Sharqia', 108.00), ('Gharbia', 108.00),
  ('Ismailia', 108.00), ('Damietta', 108.00), ('Suez', 108.00), ('Port Said', 108.00),
  ('Monufia', 108.00), ('Kafr El Sheikh', 108.00), ('Helwan', 108.00),
  ('Asyut', 128.00), ('Faiyum', 128.00), ('Sohag', 128.00), ('Beni Suef', 128.00), ('Minya', 128.00),
  ('Red Sea', 146.00), ('Qena', 146.00), ('Matrouh', 146.00), ('Aswan', 146.00), ('Luxor', 146.00),
  ('South Sinai', 169.00), ('North Sinai', 169.00), ('New Valley', 169.00)
) as v(zone, deliver)
on conflict (zone, shipment_size, effective_from) do update
  set deliver = excluded.deliver, return_to_origin = excluded.return_to_origin, updated_at = now();

notify pgrst, 'reload schema';


-- ===================== 0054_open_package_line_restored.sql =====================

-- Restore 0038's open-package split, which 0039 silently reverted.
--
-- 0039 rebased daily_pnl onto the courier-handover day, but it was written from
-- 0036's 14-column body, so the open_package_fee output column vanished and the
-- fee went back to being folded into bosta_penalty / bosta_fees_paid.
-- daily-pnl.ts still reads `r.open_package_fee ?? 0`, so the Income Statement's
-- open-package amount has been reading as zero ever since, with the money
-- silently inside the two Bosta fee lines.
--
-- Net Income was never wrong - the app's netProfit subtracts an openPackageFee
-- that was simply zero, and the fee was still being deducted inside the bundled
-- lines. What was wrong is the split: Bosta Fees Paid and Bosta Penalty each
-- carried an open-package amount that is not a courier fee, and the line meant
-- to show it showed nothing.
--
-- This is 0039's body with 0038's three fee expressions. The eff_day CASE and
-- every other expression are unchanged, so which day each mode buckets on does
-- not move - only how the same total is divided between three lines. From
-- 2026-08-04 the fee is zero anyway (0053), so this restates closed months only.
--
-- The return type changes, so the function must be dropped rather than replaced.
drop function if exists public.daily_pnl(text);
create or replace function public.daily_pnl(p_mode text)
returns table (
  day date,
  orders_placed bigint,
  orders_resolved bigint,
  delivered_count bigint,
  items_sold bigint,
  revenue numeric,
  cogs numeric,
  gross_revenue numeric,
  gross_cogs numeric,
  packaging numeric,
  bosta_penalty numeric,
  bosta_fees_paid numeric,
  cod_cash_fee numeric,
  open_package_fee numeric,
  shipping_fee_charged numeric
)
language sql
stable
as $$
  with ord as (
    select
      o.id,
      case
        when p_mode = 'performance' then o.egypt_day
        else coalesce(o.bosta_picked_up_day, o.movers_record_date)  -- actual: courier handover day
      end as eff_day,
      o.outcome,
      o.shipping_fee_charged
    from public.orders o
    where o.cancelled_at is null
  ),
  ord2 as (select * from ord where eff_day is not null),
  order_agg as (
    select
      eff_day as day,
      count(*) as orders_placed,
      count(*) filter (where outcome in ('delivered','failed_rto','exchange','pickup_return')) as orders_resolved,
      count(*) filter (where outcome = 'delivered') as delivered_count,
      sum(case when outcome is distinct from 'failed_rto' then coalesce(shipping_fee_charged,0) else 0 end) as shipping_fee_charged
    from ord2
    group by eff_day
  ),
  line_agg as (
    select
      ord2.eff_day as day,
      sum(l.quantity) as items_sold,
      sum(case when ord2.outcome = 'delivered' then coalesce(l.revenue,0) else 0 end) as revenue,
      sum(case when ord2.outcome = 'delivered'
               then coalesce(l.cost_of_goods,0) - coalesce(l.refund_adjustment,0) - coalesce(l.damage_adjustment,0)
               else 0 end) as cogs,
      sum(coalesce(l.revenue,0)) as gross_revenue,
      sum(coalesce(l.cost_of_goods,0)) as gross_cogs,
      sum(coalesce(l.packing_cost,0)) as packaging,
      -- Courier fee only, both sides (open package split out below).
      sum(case when ord2.outcome = 'failed_rto' then coalesce(l.allocated_courier_fee,0) else 0 end) as bosta_penalty,
      sum(case when ord2.outcome is distinct from 'failed_rto' then coalesce(l.allocated_courier_fee,0) else 0 end) as bosta_fees_paid,
      sum(case when ord2.outcome is distinct from 'failed_rto' then coalesce(l.allocated_cod_cash_fee,0) else 0 end) as cod_cash_fee,
      -- Open package fee on every order, any outcome.
      sum(coalesce(l.allocated_open_package_fee,0)) as open_package_fee
    from ord2
    join public.order_line_items l on l.order_id = ord2.id
    group by ord2.eff_day
  )
  select
    coalesce(oa.day, la.day) as day,
    coalesce(oa.orders_placed, 0),
    coalesce(oa.orders_resolved, 0),
    coalesce(oa.delivered_count, 0),
    coalesce(la.items_sold, 0),
    coalesce(la.revenue, 0),
    coalesce(la.cogs, 0),
    coalesce(la.gross_revenue, 0),
    coalesce(la.gross_cogs, 0),
    coalesce(la.packaging, 0),
    coalesce(la.bosta_penalty, 0),
    coalesce(la.bosta_fees_paid, 0),
    coalesce(la.cod_cash_fee, 0),
    coalesce(la.open_package_fee, 0),
    coalesce(oa.shipping_fee_charged, 0)
  from order_agg oa
  full outer join line_agg la on oa.day = la.day;
$$;

grant execute on function public.daily_pnl(text) to anon, authenticated, service_role;

notify pgrst, 'reload schema';


-- ===================== 0055_product_monthly_delivery_restore.sql =====================

-- Restores public.product_monthly_delivery() to its original four-column shape.
-- An earlier revision of this file added an in_progress column for a per-product
-- "still open" badge on the Delivery Rate tab; that badge is only wanted on the
-- Overall business row, which derives its count from the Income Statement rows
-- instead, so the per-product column had no reader.

drop function if exists public.product_monthly_delivery();

create or replace function public.product_monthly_delivery()
returns table (product_id bigint, month text, placed bigint, delivered bigint)
language sql
stable
as $$
  select
    li.product_id::bigint                                          as product_id,
    to_char(o.egypt_day, 'YYYY-MM')                                as month,
    count(*)::bigint                                               as placed,
    count(*) filter (where o.outcome = 'delivered')::bigint        as delivered
  from public.order_line_items li
  join public.orders o on o.id = li.order_id
  where li.product_id is not null
    and o.cancelled_at is null
  group by li.product_id, to_char(o.egypt_day, 'YYYY-MM');
$$;

grant execute on function public.product_monthly_delivery() to anon, authenticated, service_role;


-- ===================== 0056_self_delivered.sql =====================

-- Some Shopify orders never go through Bosta at all - they are handed to the
-- customer privately. Bosta has no record of them, so the delivery sync can
-- never resolve them: they sit at 'in_transit' forever, drag the delivery rate
-- down, and (because revenue is only recognised on a delivered order) keep
-- their revenue and COGS out of the Income Statement entirely.
--
-- The fix is to let someone record the real outcome. A privately delivered
-- order is stamped outcome = 'delivered' - so every existing rule about
-- delivered orders (revenue, COGS, delivery rate, "resolved") applies with no
-- special-casing - plus this flag, which tells the margin engine the order paid
-- no courier fee, no open-package fee and no COD cash fee, because no courier
-- ever touched it. See src/lib/engine/margin.ts.

alter table public.orders
  add column if not exists self_delivered boolean not null default false;

comment on column public.orders.self_delivered is
  'Delivered by us, not by the courier. Counts as delivered everywhere; carries no courier/open-package/COD fees.';

-- The Unresolved Orders tab reads "not cancelled and not resolved" over the
-- whole table on every load.
create index if not exists orders_outcome_open_idx
  on public.orders (egypt_day)
  where cancelled_at is null
    and coalesce(outcome, '') not in ('delivered', 'failed_rto', 'exchange', 'pickup_return');


-- ===================== 0057_self_delivered_actual_basis.sql =====================

-- An order we delivered ourselves (self_delivered, recorded on the Unresolved
-- Orders tab) has no courier handover stamp - no bosta_picked_up_day, no
-- movers_record_date - so the "actual" basis, which dates an order on the day a
-- courier collected it, found no date for it and dropped it from the report
-- entirely. It was visible in Performance and invisible in Actual.
--
-- We handed it over ourselves on the day it was placed, so that is its actual
-- date. Both mode-aware report functions get the same extra branch; everything
-- else in them is unchanged.

CREATE OR REPLACE FUNCTION public.daily_pnl(p_mode text)
 RETURNS TABLE(day date, orders_placed bigint, orders_resolved bigint, delivered_count bigint, items_sold bigint, revenue numeric, cogs numeric, gross_revenue numeric, gross_cogs numeric, packaging numeric, bosta_penalty numeric, bosta_fees_paid numeric, cod_cash_fee numeric, open_package_fee numeric, shipping_fee_charged numeric)
 LANGUAGE sql
 STABLE
AS $function$
  with ord as (
    select
      o.id,
      case
        when p_mode = 'performance' then o.egypt_day
        when o.self_delivered then o.egypt_day  -- we delivered it ourselves, on its order day
        else coalesce(o.bosta_picked_up_day, o.movers_record_date)  -- actual: courier handover day
      end as eff_day,
      o.outcome,
      o.shipping_fee_charged
    from public.orders o
    where o.cancelled_at is null
  ),
  ord2 as (select * from ord where eff_day is not null),
  order_agg as (
    select
      eff_day as day,
      count(*) as orders_placed,
      count(*) filter (where outcome in ('delivered','failed_rto','exchange','pickup_return')) as orders_resolved,
      count(*) filter (where outcome = 'delivered') as delivered_count,
      sum(case when outcome is distinct from 'failed_rto' then coalesce(shipping_fee_charged,0) else 0 end) as shipping_fee_charged
    from ord2
    group by eff_day
  ),
  line_agg as (
    select
      ord2.eff_day as day,
      sum(l.quantity) as items_sold,
      sum(case when ord2.outcome = 'delivered' then coalesce(l.revenue,0) else 0 end) as revenue,
      sum(case when ord2.outcome = 'delivered'
               then coalesce(l.cost_of_goods,0) - coalesce(l.refund_adjustment,0) - coalesce(l.damage_adjustment,0)
               else 0 end) as cogs,
      sum(coalesce(l.revenue,0)) as gross_revenue,
      sum(coalesce(l.cost_of_goods,0)) as gross_cogs,
      sum(coalesce(l.packing_cost,0)) as packaging,
      -- Courier fee only, both sides (open package split out below).
      sum(case when ord2.outcome = 'failed_rto' then coalesce(l.allocated_courier_fee,0) else 0 end) as bosta_penalty,
      sum(case when ord2.outcome is distinct from 'failed_rto' then coalesce(l.allocated_courier_fee,0) else 0 end) as bosta_fees_paid,
      sum(case when ord2.outcome is distinct from 'failed_rto' then coalesce(l.allocated_cod_cash_fee,0) else 0 end) as cod_cash_fee,
      -- Open package fee on every order, any outcome.
      sum(coalesce(l.allocated_open_package_fee,0)) as open_package_fee
    from ord2
    join public.order_line_items l on l.order_id = ord2.id
    group by ord2.eff_day
  )
  select
    coalesce(oa.day, la.day) as day,
    coalesce(oa.orders_placed, 0),
    coalesce(oa.orders_resolved, 0),
    coalesce(oa.delivered_count, 0),
    coalesce(la.items_sold, 0),
    coalesce(la.revenue, 0),
    coalesce(la.cogs, 0),
    coalesce(la.gross_revenue, 0),
    coalesce(la.gross_cogs, 0),
    coalesce(la.packaging, 0),
    coalesce(la.bosta_penalty, 0),
    coalesce(la.bosta_fees_paid, 0),
    coalesce(la.cod_cash_fee, 0),
    coalesce(la.open_package_fee, 0),
    coalesce(oa.shipping_fee_charged, 0)
  from order_agg oa
  full outer join line_agg la on oa.day = la.day;
$function$;

CREATE OR REPLACE FUNCTION public.per_product_stats(p_mode text, p_from date, p_to date)
 RETURNS TABLE(product_id bigint, variant_id bigint, orders_placed bigint, orders_resolved bigint, items_sold bigint, revenue numeric, cogs numeric)
 LANGUAGE sql
 STABLE
AS $function$
  with ord as (
    select
      o.id,
      case
        when p_mode = 'performance' then o.egypt_day
        when o.self_delivered then o.egypt_day  -- we delivered it ourselves, on its order day
        when o.courier = 'movers' then o.movers_record_date
        when o.courier = 'bosta' then o.bosta_picked_up_day
        else null
      end as eff_day,
      o.outcome
    from public.orders o
    where o.cancelled_at is null
  ),
  ord2 as (
    select * from ord where eff_day is not null and eff_day >= p_from and eff_day <= p_to
  )
  select
    l.product_id,
    l.variant_id,
    count(*) as orders_placed,
    count(*) filter (where ord2.outcome in ('delivered','failed_rto','exchange','pickup_return')) as orders_resolved,
    sum(coalesce(l.quantity, 0)) as items_sold,
    sum(coalesce(l.revenue, 0)) as revenue,
    sum(coalesce(l.cost_of_goods, 0)) as cogs
  from ord2
  join public.order_line_items l on l.order_id = ord2.id
  where l.product_id is not null
  group by l.product_id, l.variant_id;
$function$;



-- ===================== 0058_shopify_fulfillment_status.sql =====================

-- Shopify already knows which unresolved orders were hand-delivered, and it is
-- a far better signal than "has no Bosta tracking number".
--
-- An order fulfilled by a courier carries a fulfilment whose displayStatus
-- moves IN_TRANSIT -> DELIVERED and has tracking info attached. An order
-- someone marked fulfilled by hand sits at plain 'FULFILLED' forever, with no
-- tracking company, no tracking number and no delivered timestamp - because no
-- courier was ever involved. That is exactly the private-delivery case.
--
-- So store the fulfilment displayStatus alongside the outcome:
--   'FULFILLED'              -> marked fulfilled by hand, no courier
--   'IN_TRANSIT'/'DELIVERED' -> really is with a courier (sync will resolve it)
--   null                     -> never fulfilled at all
-- The Unresolved Orders tab uses it to pre-select the hand-delivered ones.

alter table public.orders
  add column if not exists shopify_fulfillment_status text;

comment on column public.orders.shopify_fulfillment_status is
  'displayStatus of the order''s Shopify fulfilments. Plain FULFILLED with no tracking = fulfilled by hand, no courier.';


-- ===================== 0059_ad_spend_segment.sql =====================

-- Miraj runs FOUR Meta ad accounts. Three are retail and pool into one retail
-- ad-spend number; the fourth is wholesale and must be reportable entirely on
-- its own (its own spend, and later its own sales).
--
-- The segment is decided by WHICH AD ACCOUNT the spend came from (see
-- src/lib/meta-accounts.ts), so it is stamped once at sync time rather than
-- being re-derived by every report.
--
-- 'retail' is the default because it is the overwhelmingly common case and
-- because TikTok spend (typed in by hand, src/lib/tiktok-spend.ts) inserts
-- rows without naming a segment.

alter table public.ad_spend
  add column if not exists segment text not null default 'retail',
  -- Which Meta ad account the row came from. The three retail accounts are
  -- POOLED in reporting, so this is not a reporting dimension - it is kept for
  -- traceability, for de-duplicating a campaign that moves between accounts,
  -- and so a mis-segmented account can be corrected with one UPDATE.
  add column if not exists ad_account_id text;

alter table public.ad_spend drop constraint if exists ad_spend_segment_check;
alter table public.ad_spend
  add constraint ad_spend_segment_check check (segment in ('retail', 'wholesale'));

-- Every P&L/report read is "spend for these days, for this segment".
create index if not exists ad_spend_segment_date_idx on public.ad_spend (segment, date);

-- An ad belongs to exactly one segment for its whole life (it lives in one ad
-- account), so the allocation mapping carries the segment too. This lets the
-- allocation popup group by segment, and stops a wholesale ad from being
-- offered against a retail-only model list.
alter table public.ad_model_assignments
  add column if not exists segment text not null default 'retail';

alter table public.ad_model_assignments drop constraint if exists ad_model_assignments_segment_check;
alter table public.ad_model_assignments
  add constraint ad_model_assignments_segment_check check (segment in ('retail', 'wholesale'));

notify pgrst, 'reload schema';


-- ===================== 0060_ad_spend_campaign_id.sql =====================

-- Name the ad-spend key for what it actually holds: a CAMPAIGN id.
--
-- This lineage began on a dashboard that allocated per AD, so ad_spend carried
-- ad_id / adset_id / adset_name. Miraj runs one CAMPAIGN per product, and the
-- Meta sync has always written campaign_id into BOTH ad_id and adset_id, with
-- campaign_name in adset_name. Two columns holding an identical value, and all
-- three named for the wrong level - which made the allocation UI read as if it
-- were mapping individual ads.
--
-- Done now because the database is still empty. After the first backfill this
-- stops being a rename and becomes a data migration.
--
-- One nuance kept in mind: for a campaign listed in ADSET_LEVEL_CAMPAIGNS
-- (src/lib/ad-split.ts) the sync deliberately stores the AD SET id here, so
-- each ad set can be allocated separately. That list is empty for Miraj. The
-- column means "the thing an allocation decision is made about", which is the
-- campaign in every case unless a campaign is explicitly split.

do $$
begin
  -- Composite unique (date, adset_id, ad_id) becomes (date, campaign_id).
  alter table public.ad_spend drop constraint if exists ad_spend_date_adset_id_ad_id_key;

  if exists (select 1 from information_schema.columns
             where table_schema='public' and table_name='ad_spend' and column_name='adset_id') then
    alter table public.ad_spend drop column adset_id;
  end if;

  if exists (select 1 from information_schema.columns
             where table_schema='public' and table_name='ad_spend' and column_name='ad_id') then
    alter table public.ad_spend rename column ad_id to campaign_id;
  end if;

  if exists (select 1 from information_schema.columns
             where table_schema='public' and table_name='ad_spend' and column_name='adset_name') then
    alter table public.ad_spend rename column adset_name to campaign_name;
  end if;

  -- Every writer sets it (the Meta sync from the API, the TikTok popup with a
  -- synthetic "tiktok:<group>" key), so it can carry a NOT NULL.
  alter table public.ad_spend alter column campaign_id set not null;

  if not exists (select 1 from pg_constraint where conname = 'ad_spend_date_campaign_key') then
    alter table public.ad_spend add constraint ad_spend_date_campaign_key unique (date, campaign_id);
  end if;

  -- The allocation mapping is keyed by the same thing.
  if exists (select 1 from information_schema.columns
             where table_schema='public' and table_name='ad_model_assignments' and column_name='ad_id') then
    alter table public.ad_model_assignments rename column ad_id to campaign_id;
  end if;
end $$;

notify pgrst, 'reload schema';


-- ===================== build verification =====================
select 'tables' as kind, count(*)::text as n from information_schema.tables
  where table_schema='public' and table_type='BASE TABLE'
union all
select 'functions', count(*)::text from information_schema.routines
  where routine_schema='public' and routine_type='FUNCTION'
union all
select 'ad_spend.campaign_id', (select count(*)::text from information_schema.columns
  where table_schema='public' and table_name='ad_spend' and column_name='campaign_id')
union all
select 'ad_spend.adset_id GONE', (select (count(*)=0)::text from information_schema.columns
  where table_schema='public' and table_name='ad_spend' and column_name='adset_id')
union all
select 'assignments.campaign_id', (select count(*)::text from information_schema.columns
  where table_schema='public' and table_name='ad_model_assignments' and column_name='campaign_id');
