-- ============================================================
--  Miraj base schema (consolidated, final state)
--  One clean build of the 18 tables the app uses, fully
--  qualified to the 'public' schema (no search_path needed).
--  Safe to re-run: drops and recreates the schema.
--  After running, add 'public' to Exposed schemas (Settings > API).
-- ============================================================

drop schema if exists public cascade;
create schema public;

-- ---------- model_groups (a "model" above individual color products) ----------
create table public.model_groups (
  id bigint generated always as identity primary key,
  name text not null,
  unit_cost numeric(12,2),
  refund_rate_override numeric(6,4),
  damage_rate_override numeric(6,4),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- products (one row per Shopify product / color) ----------
create table public.products (
  id bigint generated always as identity primary key,
  shopify_product_id bigint unique,
  name text not null,
  sku text,
  model_group_id bigint references public.model_groups(id),
  current_price numeric(12,2),
  price_synced_at timestamptz,
  unit_cost_override numeric(12,2),
  status text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- orders ----------
create table public.orders (
  id bigint generated always as identity primary key,
  shopify_order_id bigint unique not null,
  order_number text not null,
  order_created_at timestamptz not null,
  egypt_day date not null,
  total_price numeric(12,2),
  currency text default 'EGP',
  governorate_shopify text,
  cancelled_at timestamptz,
  financial_status text,
  shipping_fee_charged numeric(12,2),

  bosta_tracking_number text,
  outcome text check (outcome in ('in_transit','delivered','failed_rto','exchange','pickup_return','cancelled_return')),
  outcome_governorate text,
  attempt_number int default 1,
  cod_amount_collected numeric(12,2),
  resolved_at timestamptz,
  stock_received_at timestamptz,
  last_bosta_sync_at timestamptz,
  bosta_picked_up_day date,

  courier text check (courier in ('bosta', 'movers')),
  movers_record_date date,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index orders_egypt_day_idx on public.orders (egypt_day);
create index orders_order_number_idx on public.orders (order_number);
create index orders_bosta_picked_up_day_idx on public.orders (bosta_picked_up_day);

-- ---------- order_line_items ----------
create table public.order_line_items (
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id bigint references public.products(id),
  shopify_line_item_id bigint,
  shopify_product_id bigint,
  product_title_raw text,
  quantity int not null check (quantity > 0),
  unit_price numeric(12,2) not null,

  -- valuation engine outputs
  revenue numeric(12,2),
  cost_of_goods numeric(12,2),
  allocated_courier_fee numeric(12,2),
  allocated_cod_cash_fee numeric(12,2),
  allocated_open_package_fee numeric(12,2),
  packing_cost numeric(12,2),
  refund_adjustment numeric(12,2),
  damage_adjustment numeric(12,2),
  success_rate_used numeric(6,4),
  expected_margin numeric(12,2),
  realized_margin numeric(12,2),
  fee_breakdown jsonb,
  margin_computed_at timestamptz,

  created_at timestamptz not null default now()
);
create index order_line_items_order_id_idx on public.order_line_items (order_id);
create index order_line_items_product_id_idx on public.order_line_items (product_id);
create unique index order_line_items_shopify_line_item_id_key
  on public.order_line_items (shopify_line_item_id);

-- ---------- bosta_events (append-only courier audit trail) ----------
create table public.bosta_events (
  id bigint generated always as identity primary key,
  order_id bigint references public.orders(id),
  bosta_delivery_id text not null,
  business_reference text,
  bosta_type text,
  bosta_state text,
  attempt_number int,
  cod_amount numeric(12,2),
  governorate text,
  event_timestamp timestamptz,
  raw_payload jsonb,
  synced_at timestamptz not null default now()
);
create index bosta_events_order_id_idx on public.bosta_events (order_id);
create unique index bosta_events_delivery_id_key on public.bosta_events (bosta_delivery_id);

-- ---------- governorate_fees ----------
create table public.governorate_fees (
  governorate text primary key,
  zone text,
  updated_at timestamptz not null default now()
);
insert into public.governorate_fees (governorate) values
  ('Cairo'), ('Alexandria'), ('Giza'), ('Qalyubia'), ('Port Said'), ('Suez'),
  ('Dakahlia'), ('Sharqia'), ('Gharbia'), ('Monufia'), ('Beheira'), ('Ismailia'),
  ('Damietta'), ('Kafr El Sheikh'), ('Faiyum'), ('Beni Suef'), ('Minya'), ('Asyut'),
  ('Sohag'), ('Qena'), ('Aswan'), ('Luxor'), ('Red Sea'), ('New Valley'),
  ('Matrouh'), ('North Sinai'), ('South Sinai');

-- ---------- bosta_fee_matrix (zone x size price grid, VAT-inclusive) ----------
create table public.bosta_fee_matrix (
  zone text not null,
  shipment_size text not null,
  deliver numeric(12,2) not null,
  exchange numeric(12,2) not null,
  return_pickup numeric(12,2) not null,
  cash_collection numeric(12,2) not null,
  return_to_origin numeric(12,2) not null,
  updated_at timestamptz not null default now(),
  primary key (zone, shipment_size)
);

-- ---------- settings (single row, id = 1) ----------
create table public.settings (
  id int primary key default 1 check (id = 1),
  vat_multiplier numeric(6,4) not null default 1.14,
  cod_cash_fee_pct numeric(6,4) not null default 0,
  packing_cost_per_unit numeric(12,2) not null default 12,
  exchange_fee_base numeric(12,2) not null default 0,
  pickup_fee_base numeric(12,2) not null default 0,
  pickup_cash_refund_pct numeric(6,4) not null default 0,
  refund_rate_default numeric(6,4) not null default 0.03,
  damage_rate_default numeric(6,4) not null default 0.03,
  calibration_min_sample int not null default 150,
  calibration_min_ignore int not null default 10,
  attempt2_factor numeric(6,4) not null default 0.6,
  attempt3plus_factor numeric(6,4) not null default 0.25,
  default_box_size_tier text not null default 'Small & Medium'
    check (default_box_size_tier in ('Small & Medium','Large','X-Large','XXL (White Bag)','Light Bulky','Heavy Bulky')),
  default_success_rate_estimate numeric(6,4) not null default 0.70,
  bosta_open_package_fee numeric(12,2) not null default 7.00,
  bosta_open_package_vat_pct numeric(6,4) not null default 0.14,
  salary_employee1_monthly numeric(12,2) not null default 5000.00,
  salary_employee2_pct numeric(6,4) not null default 0.07,
  rent_monthly numeric(12,2) not null default 8000.00,
  transportation_per_day numeric(12,2) not null default 32.00,
  record_data_synced_at timestamptz,
  updated_at timestamptz not null default now()
);
insert into public.settings (id) values (1);

-- ---------- product_success_rates (calibrated per model) ----------
create table public.product_success_rates (
  model_group_id bigint not null references public.model_groups(id),
  as_of_date date not null,
  raw_rate numeric(6,4),
  resolved_sample_size int,
  store_wide_rate numeric(6,4),
  blended_rate numeric(6,4),
  attempt_adjusted_rates jsonb,
  created_at timestamptz not null default now(),
  primary key (model_group_id, as_of_date)
);

-- ---------- sync_state ----------
create table public.sync_state (
  source text primary key,
  last_synced_at timestamptz,
  cursor text,
  updated_at timestamptz not null default now()
);
insert into public.sync_state (source) values ('shopify'), ('bosta'), ('meta');

-- ---------- ad_spend (mapped to a model) ----------
create table public.ad_spend (
  id bigint generated always as identity primary key,
  date date not null,
  ad_id text,
  adset_id text not null,
  adset_name text,
  model_group_id bigint references public.model_groups(id),
  spend numeric(12,2) not null,
  currency text default 'EGP',
  -- traffic source the spend came from ('meta' | 'tiktok'); splits the P&L
  -- ad-spend line (see src/lib/reports/daily-pnl.ts, src/lib/tiktok-spend.ts).
  source text not null default 'meta',
  synced_at timestamptz not null default now(),
  unique (date, adset_id, ad_id)
);

-- ---------- monthly_delivery_rates (store-wide, per calendar month) ----------
create table public.monthly_delivery_rates (
  month date primary key,
  resolved_count int not null,
  delivered_count int not null,
  rate numeric(6,4) not null,
  computed_at timestamptz not null default now()
);

-- ---------- sku_monthly_delivery_rates (per product, per month) ----------
create table public.sku_monthly_delivery_rates (
  product_id bigint not null references public.products(id),
  month date not null,
  resolved_count int not null,
  delivered_count int not null,
  rate numeric(6,4) not null,
  created_at timestamptz not null default now(),
  primary key (product_id, month)
);

-- ---------- account_types (chart of accounts for Record Data) ----------
create table public.account_types (
  id bigint generated always as identity primary key,
  name text not null unique,
  type text not null check (type in ('income', 'expense')),
  created_at timestamptz not null default now()
);
insert into public.account_types (name, type) values
  ('Ta7selat', 'income'),
  ('Tasne3', 'expense'),
  ('Marketing', 'expense'),
  ('Subscriptions', 'expense'),
  ('Packaging', 'expense'),
  ('Transportation', 'expense'),
  ('Salary', 'expense'),
  ('Bosta', 'income'),
  ('Refund', 'expense'),
  ('Media Buyer', 'expense'),
  ('Moverz', 'income'),
  ('Other Income', 'income'),
  ('Other Expense', 'expense')
on conflict (name) do nothing;

-- ---------- recorded_transactions (manual ledger) ----------
create table public.recorded_transactions (
  id bigint generated always as identity primary key,
  date date not null,
  account_type_id bigint not null references public.account_types(id),
  type text not null check (type in ('income', 'expense')),
  description text,
  amount numeric(12,2) not null check (amount > 0),
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

-- ---------- users (app login accounts) ----------
create table public.users (
  id bigint generated always as identity primary key,
  username text not null unique,
  password_hash text not null,
  role text not null check (role in ('owner', 'staff')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ---------- model_group_cost_history (effective-dated cost timeline) ----------
create table public.model_group_cost_history (
  id bigint generated always as identity primary key,
  model_group_id bigint not null references public.model_groups(id),
  unit_cost numeric(12,2) not null,
  effective_from date not null,
  created_at timestamptz not null default now()
);
create index model_group_cost_history_model_idx
  on public.model_group_cost_history (model_group_id, effective_from);

-- ---------- ad_model_assignments (ad_id -> model mapping) ----------
create table public.ad_model_assignments (
  ad_id text primary key,
  model_group_id bigint not null references public.model_groups(id),
  created_at timestamptz not null default now()
);

-- ---------- grants so the Supabase API roles can use the schema ----------
grant usage on schema public to anon, authenticated, service_role;
grant all on all tables in schema public to anon, authenticated, service_role;
grant all on all sequences in schema public to anon, authenticated, service_role;
alter default privileges in schema public grant all on tables to anon, authenticated, service_role;
alter default privileges in schema public grant all on sequences to anon, authenticated, service_role;

notify pgrst, 'reload schema';

-- confirmation: should list all 18 base tables
select table_name from information_schema.tables where table_schema = 'public' order by table_name;
